# Generated by Django 2.1.5 on 2019-02-20 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_cate', models.CharField(max_length=50)),
                ('food_cate', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu', models.CharField(max_length=50)),
                ('cost', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('rating', models.IntegerField()),
                ('writer_name', models.CharField(max_length=50)),
                ('body', models.CharField(max_length=600)),
                ('review_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('locate', models.CharField(max_length=100)),
                ('note', models.CharField(max_length=200)),
                ('cate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Cate')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Menu')),
            ],
        ),
    ]
