# Generated by Django 2.1.5 on 2019-02-20 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cate',
            name='food_cate',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='cate',
            name='shop_cate',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='menu',
            name='cost',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='menu',
            name='menu',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='review',
            name='body',
            field=models.TextField(max_length=600),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='review',
            name='title',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='shop',
            name='locate',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='shop',
            name='name',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='shop',
            name='note',
            field=models.TextField(max_length=200),
        ),
    ]
