# Generated by Django 2.1.5 on 2019-03-03 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20190302_0502'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cate',
            name='shop',
        ),
        migrations.AddField(
            model_name='shop',
            name='food_cate',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='shop',
            name='shop_cate',
            field=models.TextField(default=''),
        ),
        migrations.DeleteModel(
            name='Cate',
        ),
    ]
